//go:build ignore

// hash_gen computes the SHA256 hash of scripts/bootstrap.sh and writes it
// to hash_generated.go as a string constant. Invoked via go:generate.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

func main() {
	// Resolve the script path relative to this source file so go:generate
	// works regardless of working directory.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "hash_gen: cannot determine source file path")
		os.Exit(1)
	}
	scriptPath := filepath.Join(filepath.Dir(thisFile), "..", "..", "scripts", "bootstrap.sh")

	content, err := os.ReadFile(scriptPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "hash_gen: failed to read %s: %v\n", scriptPath, err)
		os.Exit(1)
	}

	hash := sha256.Sum256(content)
	hashHex := hex.EncodeToString(hash[:])

	outputPath := filepath.Join(filepath.Dir(thisFile), "hash_generated.go")
	out := fmt.Sprintf(`// Code generated by hash_gen.go; DO NOT EDIT.

package bootstrap

// ScriptSHA256 is the expected SHA256 hash of scripts/bootstrap.sh,
// computed at build time via go:generate. Used to verify script integrity
// before sending user-data to EC2 (ADR-0009).
const ScriptSHA256 = %q
`, hashHex)

	if err := os.WriteFile(outputPath, []byte(out), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "hash_gen: failed to write %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	fmt.Printf("hash_gen: wrote %s (SHA256: %s)\n", outputPath, hashHex)
}
